name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Descarga el código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Instala dependencias
      - name: Install dependencies
        run: npm install

      # 4. Corre los tests con Vitest
      - name: Run tests
        run: npm run test -- --run
