name: CD - Deploy con Git Pull

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Conectarse al servidor y hacer git pull
        run: |
          ssh -o StrictHostKeyChecking=no alumno@137.184.127.11 "
            cd ~/lemp-sites/ian_ibanez &&
            git pull origin main
          "
